name: Build automÃ¡tico

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ—ï¸ Construyendo proyecto..."

  compilar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "ğŸ”§ Compilando app..."

  test:
    runs-on: ubuntu-latest
    needs: compilar
    steps:
      - run: echo "ğŸ§ª Ejecutando pruebas..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "ğŸš€ Deploy listo!"
